workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      vars:
        PROJECT_DIR: /Users/builder/clone
      ios_signing:
        distribution_type: development
        bundle_identifier: com.omerarslan.livetranslate

    scripts:
      - name: Get Flutter packages
        script: |
          cd "$PROJECT_DIR"
          pwd
          ls -la
          flutter pub get

      - name: Set up code signing
        script: |
          cd "$PROJECT_DIR"
          xcode-project use-profiles

      - name: Build iOS (IPA)
        script: |
          cd "$PROJECT_DIR"
          flutter build ipa --release

    artifacts:
      - /Users/builder/clone/build/ios/ipa/*.ipa
      - /Users/builder/clone/build/ios/archive/*.xcarchive