workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.omerarslan.livetranslate

    integrations:
      app_store_connect: codemagic

    scripts:
      - name: Get packages
        script: |
          cd /Users/builder/clone
          flutter clean
          flutter pub get

      - name: Set signing
        script: |
          cd /Users/builder/clone
          xcode-project use-profiles

      - name: Build
        script: |
          cd /Users/builder/clone
          flutter build ipa --release

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true